// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCcJo2kvlDBMIv-kfwCaYpr4anQDZw_pE',
    appId: '1:680074497371:web:ed6081f054984df278de7e',
    messagingSenderId: '680074497371',
    projectId: 'watchhub-f30a9',
    authDomain: 'watchhub-f30a9.firebaseapp.com',
    storageBucket: 'watchhub-f30a9.appspot.com',
    measurementId: 'G-TB31XZBWHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE2N7EVNW9QAk_EVw9WA-L9dWDvSi0UvU',
    appId: '1:680074497371:android:4bb1999d378b876c78de7e',
    messagingSenderId: '680074497371',
    projectId: 'watchhub-f30a9',
    storageBucket: 'watchhub-f30a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUDsnTTOGNGRxKz5AyvxxVHJ8r7NWyF2U',
    appId: '1:680074497371:ios:7c23e7340521659a78de7e',
    messagingSenderId: '680074497371',
    projectId: 'watchhub-f30a9',
    storageBucket: 'watchhub-f30a9.appspot.com',
    iosClientId: '680074497371-nbdeng0jgfjnju2j35oact2i1vj0gu7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUDsnTTOGNGRxKz5AyvxxVHJ8r7NWyF2U',
    appId: '1:680074497371:ios:3551517e07b60ab078de7e',
    messagingSenderId: '680074497371',
    projectId: 'watchhub-f30a9',
    storageBucket: 'watchhub-f30a9.appspot.com',
    iosClientId: '680074497371-fp4criikfhsjep4lvek9v8hcoa74kv15.apps.googleusercontent.com',
    iosBundleId: 'com.example.eComm.RunnerTests',
  );
}
